# -*- coding: utf-8 -*-
specialChars = (" ", "'", ",", "-", "!", "?", ".", ":")

vowels = ("a", "e", "i", "o", "u", "y")

consonants = ("b", "c", "d", "f", "g",
              "h", "j", "k", "l", "m",
              "n", "p", "q", "r", "s",
              "t", "v", "w", "x", "z")

liemrOmDictionary = {49: ["Abiosax-lie coip, Ha tior lamseqyer re ha tior ceryer poa by ma sa daqy nyr lyk",
                          "Tior ma tiocqeax sios ca lala nyr poa ha tior lamsa, mim? Tior ma tiocqeax nyr poa ha tior lamsa?",
                          "Ambiqa oma dier, by tior daqa lyk. Naos-asqa lala sqar lyk"],
                     50: ["Ma dyerimr nyr yssamcqy ky salnr as nqibacimr. Ha tior qalaqbea y k'ytymba ca tisqa riolerreim, as... as ca tisqa catiseim...",
                          "So ar nqas?",
                          "Qarneqa zeam"],
                     51: ["Im ty lymfaq!"],
                     52: ["K'Asieka! K'Asieka! K'Asieka! K'Asieka! K'Asieka!",
                          "K'Asieka co Miotayo Limca, b'ars tior!",
                          "K'Asieka! K'Asieka!"],
                     73: ["Mim! Mim! Mim! Nkor ca lyk! Mim! Nkor ca lyk! Mim!"],
                     74: ["Syirax-tior! Syirax-tior! B'ars ky caqmeaqa dier! Ha ka koqa! B'ars ky caqmeaqa dier!"
                          "Mim! Mim! Mim!",
                          "Syirax-tior! B'ars deme! B'ars nqarpoa deme!"],
                     228: ["So yoqyr ka lyk ca hioeq. So yoqyr ka lyk ca hioeq."],
                     300: ["Oma miotakka Asieka yqqeta!"],
                     310: ["Oma miotakka Asieka yqqeta! Oma miotakka Asieka yqqeta!"],
                     346: ["Co bykla! byklax-tior! Tior asar k'Asieka!, Ek ma naos qeam tior yqqetaq, tior asar k'asieka!"],
                     347: ["k'asieka!"],
                     357: ["k'asieka! tior asar k'asieka! K'asieka co Miotayo Limca!"],
                     358: ["K'asieka! K'asieka! K'asieka co Miotayo Limca!",
                           "K'asieka! K'asieka! K'asieka"],
                     359: ["K'asieka! K'asieka! K'asieka!"],
                     368: ["Tior tiuax ba poa ha seamr cyms lar lyemr? B'ars tior! B'ars tisqa carsem! B'ars ba poe ty tior yqqetaq sios y k'gaoqa!",
                           "Tior ykkax catameq elliqsakr! Tior ykkax ataekkaq k'Asieka! K'Asieka ci Miotayo Limca!",
                           "Qafyqcax ka laqtaekkaow rnabsybka poa tior ikkax mior iddqeq!",
                           "Qafyqcax ca poakka laqtaekkaora dybim tior ykkax ataekkaq k'Asieka! K'Asieka! K'Asieka! K'Asieka! K'Asieka! K'Asieka! K'Asieka ci Miotayo Limca!",
                           "K'Asieka! K'Asieka! K'Asieka! K'Asieka! K'Asieka ci Miotayo Limca!"],
                     369: ["B'asyes zayo? B'asyes zayo? B'asyes zayo, mim?",
                           "Ioe! Ioe! Ioe!",
                           "B'asyes zayo, ioe. Lyer rybgax poa by ty dyeqa lyk. Ha tior nqateamr: by ty dyeqa sqar, sqar lyk.",
                           "Tior ykkax rioddqeq, rioddqeq, rioddqeq.",
                           "Lyer ba m'ars nyr fqyta, byq tior ykkax catameq elliqsakr! Nyqba poa tior ykkax ataekkaq k'Asieka!",
                           "K'Asieka! K'Asieka! K'Asieka! K'Asieka co Miotayo Limca!"],
                     370: ["K'Asieka! K'Asieka! K'Asieka! K'Asieka co Miotayo Limca!"],
                     372: ["Po'ars-ba po'ek ces? Po'ars-ba po'ek ces? Po'ars-ba po'ek cer?"],
                     373: ["syerax-tior! syerax-tior! byklax-tior as syerax-tior!",
                           "Po'ars-ba po'ek ces? Po'ars-ba po'ek ces? Po'ars-ba po'ek ces?",
                           "Bas gilla ma nyqka misqa kymfoa. Tiaky nioqpoie tior ma ka bilnqamax nyr. Lyer m'yuax nyr naoq, ek ars om car misqar.",
                           "Ek dyes, koe yorre, nyqsea co Miotayo Limca!"],
                     375: ["Mior rillar ka Miotayo Limca."],
                     376: ["Mior rillar ka Miotayo Limca!",
                           "Ioe! Ioe! Mior rillar ka Miotayo Limca! Ioe! Ioe! Ioe!"],
                     377: ["M'yuax nyr naoq! Ek y lyk! Ek y sqar lyk! M'yuax nyr naoq! Ha tyer zeamsis, sior, tior, kezaqaq!"],
                     378: ["B'ars deme. Tior ma rioddqeqax nkor."],
                     379: ["Tior ytax tabo nioq k'Asieka as nioq ky Saqqa co Miotayo Limca.",
                           "Tior ytax rioddaqs nioq k'Asieka as nioq ky Saqqa co Miotayo Limca",
                           "Yohioqc'goi, tior ykkax lioqqeq nioq k'Asieka as nioq ky Saqqa co Miotayo Limca",
                           "Ykkax sqiotaq tisqa Asieka! Ykkax sqiotaq tisqa Saqqa!",
                           "As poa kaoq ataek mior ynniqsa ka Miotayo Limca! As poa kar bqaysoqar co Miotayo Limca bakazqams ka qasios ca lim dekr!"],
                     413: ["Ha s'yela, Bkyeqa, Kisgyeqa"]
                     }
